name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.10
  provider: ^6.0.5
  go_router: ^11.1.4
  google_fonts: ^5.1.0
  firebase_storage: ^11.5.7
  intl: ^0.19.0
  path_drawing: ^1.0.1

  # Added for json_serializable
  json_annotation: ^4.8.1
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/
