name: myapp
description: "Write Hanzi practice app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  google_sign_in: ^6.2.1
  google_fonts: ^6.3.2
  intl: ^0.20.2
  get: ^4.6.6
  just_audio: ^0.9.39
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  path_drawing: ^1.0.1
  equatable: ^2.0.5

  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: 6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/data/
