name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.2
  google_sign_in: ^6.2.1
  provider: ^6.1.5+1
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_drawing: ^1.0.1
  get: ^4.7.2
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/
