// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3h64EomQeWdzs82VWn5xvvn-KbmzZnQA',
    appId: '1:528531549397:web:50ec91988b8bc6beeec65c',
    messagingSenderId: '528531549397',
    projectId: 'testlogin-4767c',
    authDomain: 'testlogin-4767c.firebaseapp.com',
    databaseURL: 'https://testlogin-4767c-default-rtdb.firebaseio.com',
    storageBucket: 'testlogin-4767c.firebasestorage.app',
    measurementId: 'G-5061R786JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-covwWf3qt5GMBrqRTs_736VBwV6AvgM',
    appId: '1:528531549397:android:556cc048d7fc8360eec65c',
    messagingSenderId: '528531549397',
    projectId: 'testlogin-4767c',
    databaseURL: 'https://testlogin-4767c-default-rtdb.firebaseio.com',
    storageBucket: 'testlogin-4767c.firebasestorage.app',
  );
}
